//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstG2Contex : DbContext
    {
        public EstG2Contex()
            : base("name=EstG2Contex")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CausaHerida> CausaHerida { get; set; }
        public virtual DbSet<CausaMuerte> CausaMuerte { get; set; }
        public virtual DbSet<Estatus> Estatus { get; set; }
        public virtual DbSet<TipoNovedad> TipoNovedad { get; set; }
        public virtual DbSet<TipoDroga> TipoDroga { get; set; }
        public virtual DbSet<TipoApresamientos> TipoApresamientos { get; set; }
        public virtual DbSet<TipoContrabando> TipoContrabando { get; set; }
    }
}
